'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8745
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace BCU
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://microsoft.com/webservices/OfficeServer/QueryService", ConfigurationName:="BCU.QueryServiceSoap")>  _
    Public Interface QueryServiceSoap
        
        'CODEGEN: Generating message contract since the wrapper namespace (urn:Microsoft.Search) of message QueryRequest does not match the default value (http://microsoft.com/webservices/OfficeServer/QueryService)
        <System.ServiceModel.OperationContractAttribute(Action:="urn:Microsoft.Search/Query", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function Query(ByVal request As BCU.QueryRequest) As BCU.QueryResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://microsoft.com/webservices/OfficeServer/QueryService/QueryEx", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function QueryEx(ByVal queryXml As String) As System.Data.DataSet
        
        'CODEGEN: Generating message contract since the wrapper namespace (urn:Microsoft.Search) of message RegistrationRequest does not match the default value (http://microsoft.com/webservices/OfficeServer/QueryService)
        <System.ServiceModel.OperationContractAttribute(Action:="urn:Microsoft.Search/Registration", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function Registration(ByVal request As BCU.RegistrationRequest) As BCU.RegistrationResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (urn:Microsoft.Search) of message StatusRequest does not match the default value (http://microsoft.com/webservices/OfficeServer/QueryService)
        <System.ServiceModel.OperationContractAttribute(Action:="urn:Microsoft.Search/Status", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function Status(ByVal request As BCU.StatusRequest) As BCU.StatusResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://microsoft.com/webservices/OfficeServer/QueryService/GetPortalSearchInfo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetPortalSearchInfo() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://microsoft.com/webservices/OfficeServer/QueryService/GetSearchMetadata", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetSearchMetadata() As System.Data.DataSet
        
        'CODEGEN: Generating message contract since the wrapper namespace (urn:Microsoft.Search) of message RecordClickRequest does not match the default value (http://microsoft.com/webservices/OfficeServer/QueryService)
        <System.ServiceModel.OperationContractAttribute(Action:="urn:Microsoft.Search/RecordClick", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RecordClick(ByVal request As BCU.RecordClickRequest) As BCU.RecordClickResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://microsoft.com/webservices/OfficeServer/QueryService/GetQuerySuggestions", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetQuerySuggestions(ByVal queryXml As String) As String()
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Query", WrapperNamespace:="urn:Microsoft.Search", IsWrapped:=true)>  _
    Partial Public Class QueryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:Microsoft.Search", Order:=0)>  _
        Public queryXml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal queryXml As String)
            MyBase.New
            Me.queryXml = queryXml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="QueryResponse", WrapperNamespace:="urn:Microsoft.Search", IsWrapped:=true)>  _
    Partial Public Class QueryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:Microsoft.Search", Order:=0)>  _
        Public QueryResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal QueryResult As String)
            MyBase.New
            Me.QueryResult = QueryResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Registration", WrapperNamespace:="urn:Microsoft.Search", IsWrapped:=true)>  _
    Partial Public Class RegistrationRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:Microsoft.Search", Order:=0)>  _
        Public registrationXml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal registrationXml As String)
            MyBase.New
            Me.registrationXml = registrationXml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RegistrationResponse", WrapperNamespace:="urn:Microsoft.Search", IsWrapped:=true)>  _
    Partial Public Class RegistrationResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:Microsoft.Search", Order:=0)>  _
        Public RegistrationResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RegistrationResult As String)
            MyBase.New
            Me.RegistrationResult = RegistrationResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Status", WrapperNamespace:="urn:Microsoft.Search", IsWrapped:=true)>  _
    Partial Public Class StatusRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="StatusResponse", WrapperNamespace:="urn:Microsoft.Search", IsWrapped:=true)>  _
    Partial Public Class StatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:Microsoft.Search", Order:=0)>  _
        Public StatusResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal StatusResult As String)
            MyBase.New
            Me.StatusResult = StatusResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecordClick", WrapperNamespace:="urn:Microsoft.Search", IsWrapped:=true)>  _
    Partial Public Class RecordClickRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:Microsoft.Search", Order:=0)>  _
        Public clickInfoXml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal clickInfoXml As String)
            MyBase.New
            Me.clickInfoXml = clickInfoXml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecordClickResponse", WrapperNamespace:="urn:Microsoft.Search", IsWrapped:=true)>  _
    Partial Public Class RecordClickResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface QueryServiceSoapChannel
        Inherits BCU.QueryServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class QueryServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of BCU.QueryServiceSoap)
        Implements BCU.QueryServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function BCU_QueryServiceSoap_Query(ByVal request As BCU.QueryRequest) As BCU.QueryResponse Implements BCU.QueryServiceSoap.Query
            Return MyBase.Channel.Query(request)
        End Function
        
        Public Function Query(ByVal queryXml As String) As String
            Dim inValue As BCU.QueryRequest = New BCU.QueryRequest
            inValue.queryXml = queryXml
            Dim retVal As BCU.QueryResponse = CType(Me,BCU.QueryServiceSoap).Query(inValue)
            Return retVal.QueryResult
        End Function
        
        Public Function QueryEx(ByVal queryXml As String) As System.Data.DataSet Implements BCU.QueryServiceSoap.QueryEx
            Return MyBase.Channel.QueryEx(queryXml)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function BCU_QueryServiceSoap_Registration(ByVal request As BCU.RegistrationRequest) As BCU.RegistrationResponse Implements BCU.QueryServiceSoap.Registration
            Return MyBase.Channel.Registration(request)
        End Function
        
        Public Function Registration(ByVal registrationXml As String) As String
            Dim inValue As BCU.RegistrationRequest = New BCU.RegistrationRequest
            inValue.registrationXml = registrationXml
            Dim retVal As BCU.RegistrationResponse = CType(Me,BCU.QueryServiceSoap).Registration(inValue)
            Return retVal.RegistrationResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function BCU_QueryServiceSoap_Status(ByVal request As BCU.StatusRequest) As BCU.StatusResponse Implements BCU.QueryServiceSoap.Status
            Return MyBase.Channel.Status(request)
        End Function
        
        Public Function Status() As String
            Dim inValue As BCU.StatusRequest = New BCU.StatusRequest
            Dim retVal As BCU.StatusResponse = CType(Me,BCU.QueryServiceSoap).Status(inValue)
            Return retVal.StatusResult
        End Function
        
        Public Function GetPortalSearchInfo() As String Implements BCU.QueryServiceSoap.GetPortalSearchInfo
            Return MyBase.Channel.GetPortalSearchInfo
        End Function
        
        Public Function GetSearchMetadata() As System.Data.DataSet Implements BCU.QueryServiceSoap.GetSearchMetadata
            Return MyBase.Channel.GetSearchMetadata
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function BCU_QueryServiceSoap_RecordClick(ByVal request As BCU.RecordClickRequest) As BCU.RecordClickResponse Implements BCU.QueryServiceSoap.RecordClick
            Return MyBase.Channel.RecordClick(request)
        End Function
        
        Public Sub RecordClick(ByVal clickInfoXml As String)
            Dim inValue As BCU.RecordClickRequest = New BCU.RecordClickRequest
            inValue.clickInfoXml = clickInfoXml
            Dim retVal As BCU.RecordClickResponse = CType(Me,BCU.QueryServiceSoap).RecordClick(inValue)
        End Sub
        
        Public Function GetQuerySuggestions(ByVal queryXml As String) As String() Implements BCU.QueryServiceSoap.GetQuerySuggestions
            Return MyBase.Channel.GetQuerySuggestions(queryXml)
        End Function
    End Class
End Namespace
